PLUGIN_NAME=		switchtracker
PLUGIN_VERSION=		1.0
PLUGIN_COMMENT=		Track and monitor network switches via LLDP and SNMP
PLUGIN_DEPENDS=		os-lldpd net-snmp
PLUGIN_MAINTAINER=	gitzone83@gmail.com

.include "../../Mk/plugins.mk"
